import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("logout", "routes/logout.tsx"),
  route("verify", "routes/verify.tsx"),
  route("forgot", "routes/forgot.tsx"),
  route("reset", "routes/reset.tsx"),
  route("device", "routes/device.tsx"),
  route("oauth/authorize", "routes/oauth-authorize.tsx"),
  route("new", "routes/new.tsx"),
  route("settings", "routes/settings.tsx"),
  route("explore", "routes/explore.tsx", { id: "explore" }),
  route("search", "routes/explore.tsx", { id: "search" }),
  route("workspaces/new", "routes/workspace-new.tsx"),
  route(":owner", "routes/workspace.tsx"),
  route(":owner/:repo", "routes/repo/layout.tsx", [
    index("routes/repo/code.tsx"),
    route("tree/:ref/*", "routes/repo/tree.tsx"),
    route("blob/:ref/*", "routes/repo/blob.tsx"),
    route("commits", "routes/repo/commits.tsx"),
    route("issues", "routes/repo/issues.tsx"),
    route("issues/new", "routes/repo/issue-new.tsx"),
    route("issues/:number", "routes/repo/issue.tsx"),
    route("pulls", "routes/repo/pulls.tsx"),
    route("pull/:number", "routes/repo/pull.tsx"),
  ]),
] satisfies RouteConfig;
